title: "李婷 Ting Li"
description: "李婷的中文学术主页"
url: "https://Skytingli.github.io"
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai
markdown: kramdown
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

