# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site,
# values which you are expected to set up once and rarely need to edit
# after that.

# Basic Site Settings

locale                   : "zh-CN"

site_theme               : "default"

title                    : "李婷 Ting Li"

title_separator          : "-"

name                     : &name "李婷 Ting Li"

description              : &description "李婷，江西财经大学数字经济学院产业经济学博士研究生个人学术主页"

url                      : "https://Skytingli.github.io"

baseurl                  : ""

repository               : "Skytingli/Skytingli.github.io"


# Site Author

author:

  avatar           : "profile.jpg"

  name             : "李婷<br><span class='author__english-name'>Ting Li</span>"

  pronouns         :

  bio              : "产业经济学博士研究生<br>江西财经大学<br><br><strong>研究方向</strong><br>数字经济<br>产业经济<br>资源与环境经济学"

  location         : "江西 南昌"

  employer         :

  uri              :

  email            : "liting4891@163.com"


  # Academic websites

  academia         :

  arxiv            :

  googlescholar    :

  inspire-hep      :

  impactstory      :

  orcid            :

  semantic         :

  ssrn             :

  pubmed           :

  researchgate     :

  scopus           :

  zotero           :


  # Repositories

  bitbucket        :

  codepen          :

  dribbble         :

  github           :

  kaggle           :

  stackoverflow    :


  # Social media

  artstation       :

  bluesky          :

  facebook         :

  flickr           :

  foursquare       :

  goodreads        :

  google_plus      :

  keybase          :

  instagram        :

  lastfm           :

  linkedin         :

  mastodon         :

  medium           :

  pinterest        :

  soundcloud       :

  steam            :

  telegram         :

  tumblr           :

  twitter          :

  vine             :

  weibo            :

  wikipedia        :

  xing             :

  youtube          :

  zhihu            :


# Publication Category

publication_category:

  books:

    title: 'Books'

  manuscripts:

    title: 'Journal Articles'

  conferences:

    title: 'Conference Papers'


# Site Settings

teaser                   :

breadcrumbs              : false

words_per_minute         : 160

future                   : true

read_more                : "disabled"

talkmap_link             : false


comments:

  provider               :


atom_feed:

  hide                   : false

  path                   :


# SEO Related

google_site_verification :

bing_site_verification   :

alexa_site_verification  :

yandex_site_verification :


# Social Sharing

twitter:

  username               :


facebook:

  username               :

  app_id                 :

  publisher              :


og_image                 :

og_description           :


social:

  type                   :

  name                   :

  links:
  # Analytics

analytics:

  provider               : "false"

  google:

    tracking_id          :


# Reading Files

include:

  - .htaccess

  - _pages

  - files


exclude:

  - "*.sublime-project"

  - "*.sublime-workspace"

  - .asset-cache

  - .bundle

  - .github

  - .jekyll-assets-cache

  - .sass-cache

  - assets/js/_main.js

  - assets/js/plugins

  - assets/js/vendor

  - CHANGELOG

  - Capfile

  - config

  - Dockerfile

  - Gemfile

  - Gruntfile.js

  - gulpfile.js

  - LICENSE

  - local

  - log

  - node_modules

  - package.json*

  - Rakefile

  - README

  - tmp


keep_files:

  - .git

  - .svn


encoding: "utf-8"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"



# Conversion

markdown: kramdown

highlighter: rouge

lsi: false

excerpt_separator: "\n\n"

incremental: false



# Markdown Processing

kramdown:

  input: GFM

  hard_wrap: false

  auto_ids: true

  footnote_nr: 1

  entity_output: as_char

  toc_levels: 1..6

  smart_quotes: lsquo,rsquo,ldquo,rdquo

  enable_coderay: false



# Collections

collections:

  teaching:

    output: true

    permalink: /:collection/:path/


  publications:

    output: true

    permalink: /:collection/:path/


  portfolio:

    output: true

    permalink: /:collection/:path/


  talks:

    output: true

    permalink: /:collection/:path/



# Defaults

defaults:


  - scope:

      path: ""

      type: posts

    values:

      layout: single

      author_profile: true

      read_time: true

      comments: true

      share: true

      related: true


  - scope:

      path: ""

      type: pages

    values:

      layout: single

      author_profile: true


  - scope:

      path: ""

      type: teaching

    values:

      layout: single

      author_profile: true

      share: true

      comments: true


  - scope:

      path: ""

      type: publications

    values:

      layout: single

      author_profile: true

      share: true

      comments: true


  - scope:

      path: ""

      type: portfolio

    values:

      layout: single

      author_profile: true

      share: true

      comment: true


  - scope:

      path: ""

      type: talks

    values:

      layout: talk

      author_profile: true

      share: true



# Sass/SCSS

sass:

  sass_dir: _sass

  load_paths:

    - _sass

    - vendor

  style: compressed



# Outputting

permalink: /:categories/:title/

timezone: Etc/UTC



# Plugins

plugins:

  - jekyll-feed

  - jekyll-gist

  - jekyll-paginate

  - jekyll-sitemap

  - jekyll-redirect-from

  - jemoji



# Mimic GitHub Pages with --safe

whitelist:

  - jekyll-feed

  - jekyll-gist

  - jekyll-paginate

  - jekyll-sitemap

  - jekyll-redirect-from

  - jemoji



# Archives

category_archive:

  type: liquid

  path: /categories/


tag_archive:

  type: liquid

  path: /tags/



# HTML Compression

compress_html:

  clippings: all

  ignore:

    envs: development
